# Generated by Django 4.0 on 2021-12-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='video_url',
            field=models.URLField(max_length=300),
        ),
    ]
